### ISSUE TITLE
logo.zip图标背景颜色、文字大小不统一，强迫症不能忍……然后自己画了一套，望采纳

### ISSUE THREAD

**Issue by FunnyFly-ZW** [huangqian8/SwitchPlugins#1]
预览：
![icon_ams](https://github.com/huangqian8/SwitchPlugins/assets/41453032/28107c12-5b7a-4f14-8353-c25b1b70ad8a)
![icon_Atmosphere_emunand](https://github.com/huangqian8/SwitchPlugins/assets/41453032/606ca164-c12d-4798-88ed-978b762eb9ab)
![icon_Atmosphere_sysnand](https://github.com/huangqian8/SwitchPlugins/assets/41453032/d7bcda83-f39d-406f-b1ed-4bd0fc5659b2)
![icon_stock](https://github.com/huangqian8/SwitchPlugins/assets/41453032/dd9fe22c-98ab-4e31-b884-7baafbfb315e)
bmp不能上传，打包在这里：[logo.zip](https://github.com/huangqian8/SwitchPlugins/files/14099845/logo.zip)

**Comment by huangqian8** [comment]
感谢分享！已集成！
之前一直没注意这个，替换后果然美观了很多。
